output   = "models"
wipe     = true
no-tests = true

[psql]
    dbname = "summarist"
    host = "localhost"
    port = 5432
    user = "user"
    pass = "password"
    schema = "public"
    sslmode = "disable"
    blacklist = ["schema_migrations"]
